void print_triangle(int size);
void fizz_buzz(void);
void print_square(int size);
void print_line(int i);
int _isupper(int c);
int _isdigit(int c);
void print_numbers(void);
int _putchar(char c);
void print_most_numbers(void);
void more_numbers(void);
void _printNum(int i);
void print_diagonal(int i);
